# Generated by Django 3.2.8 on 2021-10-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchatapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=100),
            preserve_default=False,
        ),
    ]
