# Generated by Django 3.2.8 on 2021-10-30 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chitchatapi', '0003_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=280)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chitchatapi.user')),
            ],
        ),
    ]
