# Generated by Django 3.2.8 on 2021-10-30 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chitchatapi', '0005_auto_20211030_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='chitchatapi.chat'),
            preserve_default=False,
        ),
    ]
