# Generated by Django 3.2.8 on 2021-10-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchatapi', '0006_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='recipient',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to='chitchatapi.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(to='chitchatapi.Chat'),
        ),
    ]
