# Generated by Django 3.2.8 on 2021-11-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchatapi', '0008_alter_user_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Password01', max_length=100),
            preserve_default=False,
        ),
    ]
