# Generated by Django 3.2.9 on 2021-12-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchatapi', '0010_auto_20211129_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_image',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/134/134914.png', max_length=1000),
            preserve_default=False,
        ),
    ]
